### PR TITLE
Add support for Nvidia Jetson hw

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
Added support for Nvidia Jetson hardware, GPUs supported:
- [Jetson AGX Orin](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/), [Jetson Orin NX](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/), [Jetson Orin Nano](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-orin/) 	8.7
- [Jetson AGX Xavier](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-agx-xavier/), [Jetson Xavier NX](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-xavier-nx/) 	7.2
- [Jetson TX2](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-tx2/) 	6.2
- [Jetson Nano](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-nano/) 	5.3

reference - https://developer.nvidia.com/cuda-gpus

### CODE REVIEW

**Comment by IamShubhamGupto** [comment]
Hello @tridao @albertfgu 
I am using mamba package on Nvidia Jetson GPUs, specifically AGX Xavier. The current `setup.py` does not account the GPUs cuda compatibility. The following changes allows me to use `mamba_ssm` with CUDA support on these GPUs 

related https://github.com/state-spaces/mamba/issues/40 and #209 

While the build currently works, it does not have CUDA kernel support. This PR addresses the issue

Let me know if further modifications are required

**Comment by AZong76** [comment]
Hello, I encountered this issue while trying to install Mamba on Jetson Agx Orin.
May I ask how to solve it? I tried to install Triton, but it failed.


(sctnet) learningx@learningx-desktop:~/upan/mamba/mamba-1.1.1$ MAMBA_FORCE_BUILD=TRUE pip install .
Processing /home/learningx/upan/mamba/mamba-1.1.1
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/learningx/upan/anaconda3/envs/sctnet/lib/python3.8/site-packages (from mamba_ssm==1.1.1) (1.12.0a0+2c916ef.nv22.3)
Requirement already satisfied: packaging in /home/learningx/upan/anaconda3/envs/sctnet/lib/python3.8/site-packages (from mamba_ssm==1.1.1) (24.0)
Requirement already satisfied: ninja in /home/learningx/upan/anaconda3/envs/sctnet/lib/python3.8/site-packages (from mamba_ssm==1.1.1) (1.11.1.1)
Requirement already satisfied: einops in /home/learningx/upan/anaconda3/envs/sctnet/lib/python3.8/site-packages (from mamba_ssm==1.1.1) (0.7.0)
INFO: pip is looking at multiple versions of mamba-ssm to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement triton (from mamba-ssm) (from versions: none)
ERROR: No matching distribution found for triton

**Comment by AZong76** [comment]
image
Hello, I tried downloading the source code to build a triton on Jetson Agx Orin, but I kept getting stuck in the building interface. Do you know the reason for this?

**Comment by AZong76** [comment]
I've been waiting for an hour and still haven't made any progress.

> image Hello, I tried downloading the source code to build a triton on Jetson Agx Orin, but I kept getting stuck in the building interface. Do you know the reason for this?

**Comment by IamShubhamGupto** [comment]
Hello!

I recently added a PR that allows CUDA support for `mamba_ssm` and
`causal-conv1d`. In order to use it, clone from the latest commit on the
main branch and run the following command for both the repositories -
`python3 setup.py install` This will build the wheel specifically for the
jetson agx orin. I hope this helps. You also need to make sure you're
running CUDA 11.6+. You can verify using `nvcc --version`.

**Pull request merged**
